# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxxRyKmk6rPjJ_mxSm8Anan1xH8o3ytb
"""

score = input("請輸入成績").split()
i = 0

for s in score:
  if int(s) < 60:
    i = i + 1
    continue

print(i)