# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxxRyKmk6rPjJ_mxSm8Anan1xH8o3ytb
"""

score = input("請輸入成績").split()

MaxScore = 0
MinScore = 100

for s in score:
  if int(s) > MaxScore:
    MaxScore = int(s)
  elif int(s) < MinScore:
    MinScore = int(s)

print(MaxScore)
print(MinScore)

for s in score:
  total = total + int(s)
  if int(s) < 60:
    i = i + 1
    continue

score_average = total / len(score)
print('平均數:',score_average)
print(i)